# For developers.google.com
safe: false
port: 8081
source: src/site
destination: ./src/appengine/build/devsite
markdown: kramdown
permalink: /articles/:title.html
fundamentals: /web/fundamentals
baseurl: /web
url: /web
highlighter: pygments
pygments: true
github:
  root: https://github.com/Google/WebFundamentals
  content: tree/master/src/site
include_open_html: false
spotlights: false
custom:
kramdown:
  toc_levels: "2"
  entity_output: :as_input
include: ['.htaccess', '_project.yaml', '_book.yaml']
exclude: ['README.md', '*.rb', '*.psd', 'js/*', '*.pxm', 'npm-debug.log']
langs_available: ['ar', 'de', 'es', 'fr', 'he', 'it', 'ja', 'ko', 'nl', 'pl', 'pt-br', 'ru', 'tr', 'zh-cn', 'zh-tw']
sample_link_base: "http://googlesamples.github.io/web-fundamentals/samples/"
